# Generated by Django 5.0 on 2023-12-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligiblity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer',
            field=models.IntegerField(default=0),
        ),
    ]
