# Generated by Django 5.0 on 2023-12-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligiblity', '0003_remove_customer_current_debt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
